<a href="https://colab.research.google.com/github/m1ksu0/Pytorch-Testing/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np

LIST

In [3]:
my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

NUMPY ARRAYS

In [5]:
np1 = np.random.rand(3,4)
np1

array([[0.66543045, 0.60999807, 0.01346969, 0.20462981],
       [0.52975066, 0.64436879, 0.96878452, 0.16966428],
       [0.71455852, 0.32462526, 0.49384277, 0.76921453]])

In [6]:
np1.dtype

dtype('float64')

TENSORS

In [7]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 1.7133, -0.6031,  1.9592, -0.2259],
        [-0.2632,  0.0183, -2.4787,  0.1246],
        [-0.8616,  0.4195,  0.0060,  1.8613]])

In [8]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [9]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.6654, 0.6100, 0.0135, 0.2046],
        [0.5298, 0.6444, 0.9688, 0.1697],
        [0.7146, 0.3246, 0.4938, 0.7692]], dtype=torch.float64)